version: "3"

services:
  backend:
    build: 
      context: 'backend'
      dockerfile: 'Dockerfile.test'
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - backend
      - db

  database:
    image: mongo
    expose:
      - 27017
    networks:
      - db
  mongosetup:
    image: mongo
    entrypoint: ["mongorestore", "--host", "database", "/dump"]
    volumes:
      - ./database/dump:/dump
    depends_on: 
      - database
    logging:
      driver: "none"
    networks:
      - db


networks:
  backend:
  db: